# Define the publishing rate, must be positive.
publish_rate: 25

# Define the frames we care about. Each frame is associated with a pose topic
# (mandatory), and optionally a parent frame (default=world) and
# initial_position (default=None).
frames:
    dope/pose_soup:
        pose_topic: dope/pose_soup
        parent_frame: camera_color_optical_frame
        initial_position: 0.0 0.0 0.0
